### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alaneje** [DiscordUnity/DiscordUnity#5]
Hey, was trying this out to see if I could use it for something I want to do, but I keep getting these errors when I try logging in! 
![image](https://cloud.githubusercontent.com/assets/5552316/18385373/1c34a168-7688-11e6-9ffe-d1c3ba3ba9af.png)

**Comment by DatBlindArcher** [comment]
This is a known thing to happen if you're using Unity with a version higher than 5.4.
Since the lib is a bit outdated, because I'm waiting for some discord features, try to stay below 5.4.

**Comment by alaneje** [comment]
Do you have an estimated time on when you'll be able to update it to 5.4? :) Thanks for quick response!

**Comment by DatBlindArcher** [comment]
I'm sorry I don't have an estimated time because the discord devs don't know either when it will be there.

**Comment by alaneje** [comment]
That's fair enough, I'll keep my eye out, Thanks for letting me know! :)

**Comment by alaneje** [comment]
Forgot to close this when you updated the api, so I'll close this now, thank you :)
